modLoader="javafml"
loaderVersion="[1,)"
license="LGPL v2.1 (code), CC-BY 4.0 (assets)"
issueTrackerURL="https://github.com/EnderTurret/RainRot/issues"

[[mods]]
    modId="rainrot"
    displayName="Rain Rot"
    description='''
    A Minecraft mod that adds a bunch of things from Rain World, such as plushies.
    '''
    version="${file.jarVersion}"
    authors="EnderTurret, PuffballFungus"
    credits="cmusounddesign on freesound, for the vending machine dispense sound"
    displayURL="https://github.com/EnderTurret/RainRot"
    logoFile="icon.png"

[[dependencies.rainrot]]
    modId="forge"
    mandatory=true
    versionRange="[47,48)"
    ordering="NONE"
    side="BOTH"

[[dependencies.rainrot]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.20.2)"
    ordering="NONE"
    side="BOTH"